server:
  port: 8888

spring:
  application:
    name: 'fornecedor'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/brunojacob89/microservice-repo
          searchPaths: fornecedor